api_platform:
    title: Hello API Platform
    version: 1.0.0
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/json']
    swagger:
        versions: [3]
    # Good cache defaults for REST APIs
    defaults:
        stateless: true
        route_prefix: '/api'
        pagination_items_per_page: 15
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
